import { readFile, writeFile } from "node:fs/promises";
import postcss from "postcss";

export async function buildCss() {
  const engineCss = await readFile("node_modules/@fortune-sheet/react/dist/index.css", "utf8");
  const css = postcss.parse(engineCss);
  css.walkRules(rule => {
    if (rule.parent.type === "atrule" && /keyframes$/i.test(rule.parent.name)) return;
    rule.selectors = rule.selectors.map(selector => {
      if (/^(html|body|:root)(?=\b|:)/.test(selector)) {
        return selector.replace(/^(html|body|:root)/, ".obsidian-spreadsheet");
      }
      return `.obsidian-spreadsheet ${selector}`;
    });
  });
  const overrides = await readFile("spreadsheet.css", "utf8");
  await writeFile("styles.css", "/* Generated by build-css.mjs from FortuneSheet and spreadsheet.css. */\n" + css.toString() + "\n" + overrides);
}
