import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { buildCss } from "./build-css.mjs";
import { readFile } from "node:fs/promises";
import { patchEngine, patchCore, patchBooleanLiterals } from "./engine-compat.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
await buildCss();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	plugins: [{
		name: "fortune-compatibility",
		setup(build) {
			build.onLoad({ filter: /@fortune-sheet[\\/]formula-parser[\\/](?:es|lib)[\\/]parser\.js$/ }, async args => ({
				contents: patchBooleanLiterals(await readFile(args.path, "utf8")), loader: "js",
			}));
			build.onLoad({ filter: /@fortune-sheet[\\/]react[\\/]dist[\\/]index(?:\.esm)?\.js$/ }, async args => ({
				contents: patchEngine(await readFile(args.path, "utf8")), loader: "js",
			}));
			build.onLoad({ filter: /@fortune-sheet[\\/]core[\\/]dist[\\/]index(?:\.esm)?\.js$/ }, async args => ({
				contents: patchCore(await readFile(args.path, "utf8")), loader: "js",
			}));
		},
	}],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	define: { "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development") },
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
